import { Button, VerticalBox, LineEdit} from "std-widgets.slint";

export component AppWindow inherits Window {

    in property <string> results: "";
    in-out property <bool> opencurtain;
    callback divide-income(string);

    background: #313e50;
    GridLayout {
        padding: 50px;
        spacing: 5px;
        Row {
            Text {
                text: "Enter total purchase value";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }
        Row {
            income := LineEdit {
                font-size: 16px;
                horizontal-alignment: center;
                placeholder-text: "14000";
                height: 35px;
            }
        }
        Row {
            Button {
                text: "Calculate";
                primary: true;
                height: 35px;
                clicked => { divide-income(income.text)}
            }
        }
        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                }
            }
        }
    }
}
